### PR TITLE
fix(build): update keycloak version dependency to fix NoSuchMethodError on 21.0.2

### PR DESCRIPTION
**Pull request by Ken-Michalak**
> ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-29) Uncaught server error: java.lang.NoSuchMethodError: 'org.jboss.resteasy.spi.HttpRequest org.keycloak.authentication.AuthenticationFlowContext.getHttpRequest()'

### CODE REVIEW

**Comment by jspizziri** [comment]
@Ken-Michalak is this a breaking change in any way?

**Comment by Ken-Michalak** [comment]
I'd guess that it wouldn't work on older versions of Keycloak (maybe before 20). The odd part is that the code that was trying to call the method wasn't in this repo at all. Maybe some deps are packaged in the jar, but others were just calling the versions pulled in by Keycloak.

**Comment by Ken-Michalak** [comment]
@jspizziri do we have to tag it or run that release.js manually?

**Comment by jspizziri** [comment]
@Ken-Michalak https://github.com/5-stones/keycloak-email-otp#release

**Comment by Ken-Michalak** [comment]
@jspizziri There's a tag now, but the ci still didn't pick up on it.

**Comment by jspizziri** [comment]
Looks like it just took a second. It's there now.

**Pull request merged**
